apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: stxv34vof-dotnet-basic-gitops
  description: This is GitOps manifest for stxv34vof-dotnet-basic   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: stxv34vof-dotnet-basic
    janus-idp.io/tekton: stxv34vof-dotnet-basic
    backstage.io/kubernetes-id: stxv34vof-dotnet-basic 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:stxv34vof-dotnet-basic
